apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-test-pruning 
  janus-idp.io/tekton: test-test-pruning
  backstage.io/kubernetes-id: test-test-pruning
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: test-test-pruning
resources: 
- application-dev.yaml